// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxh-HR-edkUbuf1jlziQmRlMEHL4FL_sQ',
    appId: '1:276832274178:web:17705214149a242be4241b',
    messagingSenderId: '276832274178',
    projectId: 'bktmobileapp-642da',
    authDomain: 'bktmobileapp-642da.firebaseapp.com',
    storageBucket: 'bktmobileapp-642da.firebasestorage.app',
    measurementId: 'G-F7GMF5SL4Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6S2Z4sgMT2fPt2iaevednUdub2Ph6AXk',
    appId: '1:276832274178:android:0cb400a31546f977e4241b',
    messagingSenderId: '276832274178',
    projectId: 'bktmobileapp-642da',
    storageBucket: 'bktmobileapp-642da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjQEHXvbHotoNLd_WazTMevWdoh1-fzuc',
    appId: '1:276832274178:ios:4faf68c9e2ff77cce4241b',
    messagingSenderId: '276832274178',
    projectId: 'bktmobileapp-642da',
    storageBucket: 'bktmobileapp-642da.firebasestorage.app',
    iosClientId: '276832274178-ibgc9tg4ct3mi03p6ujmhlc389imc45o.apps.googleusercontent.com',
    iosBundleId: 'coin.bookmyteacher.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjQEHXvbHotoNLd_WazTMevWdoh1-fzuc',
    appId: '1:276832274178:ios:f2296384d3f3e868e4241b',
    messagingSenderId: '276832274178',
    projectId: 'bktmobileapp-642da',
    storageBucket: 'bktmobileapp-642da.firebasestorage.app',
    iosClientId: '276832274178-o968dmtqq2roq56gajr77c3u28032k98.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxh-HR-edkUbuf1jlziQmRlMEHL4FL_sQ',
    appId: '1:276832274178:web:85f5469e471ad4fde4241b',
    messagingSenderId: '276832274178',
    projectId: 'bktmobileapp-642da',
    authDomain: 'bktmobileapp-642da.firebaseapp.com',
    storageBucket: 'bktmobileapp-642da.firebasestorage.app',
    measurementId: 'G-XGYLSFNC35',
  );
}
